version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_api
      - POSTGRES_USER=eric
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
